version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: solvo_postgres
    environment:
      POSTGRES_USER: solvo
      POSTGRES_PASSWORD: solvo_secret
      POSTGRES_DB: solvo_db
    ports:
      - "5432:5432"
    volumes:
      - solvo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solvo -d solvo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  solvo_pgdata:
